#!/bin/bash
cwd=`pwd`
if (( $# > 0 )); then
    cmd="/usr/local/php/bin/php -S 0.0.0.0:"$1" -c /usr/local/php/etc/php.ini -t "$cwd" router.php"
    $cmd > $cwd/logs 2>&1 &
    echo 'started'
else
    echo 'port required';
fi
